manifest:
  projects:
    - name: nrf
      url: https://github.com/nrfconnect/sdk-nrf
      revision: v3.1.0
      import: true
      import:
        path-blocklist: modules/lib/memfault-firmware-sdk
        name-blocklist:
          # unused, save the download
          - matter
    - name: memfault-firmware-sdk
      url: https://github.com/memfault/memfault-firmware-sdk
      path: modules/lib/memfault-firmware-sdk
      revision: master
  self:
    path: memfault_demo_app
    import: submanifests
